[env.production]
name = "beer-link"
compatibility_date = "2024-05-04"
compatibility_flags = ["nodejs_compat"]

# 必要な環境変数をここに追加してください
# 例：
# [env.production.vars]
# API_URL = "https://api.example.com"
# FIREBASE_API_KEY = "your-api-key"

[site]
bucket = ".vercel/output/static"
